#!/bin/bash
build=build/channelfinder

rm -rf dist
rm -rf build

mkdir dist
mkdir -p ${build}/{war,ldif}

cp target/ChannelFinder.war ${build}/war
cp ldif/*.ldif ${build}/ldif

cd build
tar -czvf ../dist/channelfinder.tar.gz channelfinder
cd ..
