#!/bin/bash
set build=build/channelfinder

cd channelfinder
rm -rf dist
mkdir -p ${build}/etc/{wars,sql,ldif}
mkdir dist

cp ../target/ChannelFinder.war ${build}/etc/wars
cp sql/*.sql ${build}/etc/sql
#cp sql/upgrade/*.sql ${build}/etc/sql/upgrade
cp ldif/*.ldif ${build}/etc/ldif

cd build
tar -czvf ../dist/channelfinder.tar.gz channelfinder
cd ../..
