#!/bin/bash
build=build/channelfinder

rm -rf dist
rm -rf build

mkdir dist
mkdir -p ${build}/{war,sql,ldif}

cp target/ChannelFinder.war ${build}/war
cp sql/*.sql ${build}/sql
#cp sql/upgrade/*.sql ${build}/sql/upgrade
cp ldif/*.ldif ${build}/ldif

cd build
tar -czvf ../dist/channelfinder.tar.gz channelfinder
cd ../..
